const PLATFORM_ROLES = {
  SUPER_ADMIN: 'super_admin',
  SUPPORT_ADMIN: 'support_admin',
  BILLING_ADMIN: 'billing_admin',
};

const PLATFORM_ROLE_GROUPS = {
  FULL_ACCESS: [
    PLATFORM_ROLES.SUPER_ADMIN,
  ],

  SUPPORT: [
    PLATFORM_ROLES.SUPER_ADMIN,
    PLATFORM_ROLES.SUPPORT_ADMIN,
  ],

  BILLING: [
    PLATFORM_ROLES.SUPER_ADMIN,
    PLATFORM_ROLES.BILLING_ADMIN,
  ],

  ANY_PLATFORM_ADMIN: [
    PLATFORM_ROLES.SUPER_ADMIN,
    PLATFORM_ROLES.SUPPORT_ADMIN,
    PLATFORM_ROLES.BILLING_ADMIN,
  ],
};

module.exports = {
  PLATFORM_ROLES,
  PLATFORM_ROLE_GROUPS,
};
